apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-galeria.fullname" . }}
  labels:
    app: {{ include "mariadb-galeria.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app: {{ include "mariadb-galeria.fullname" . }}
