apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-galeria.fullname" . }}-headless
  labels:
    app: {{ include "mariadb-galeria.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: mysql
  clusterIP: None
  selector:
    app: {{ include "mariadb-galeria.fullname" . }}