apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mariadb-galeria.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "mariadb-galeria.fullname" . }}
  serviceName: "{{ include "mariadb-galeria.fullname" . }}-headless"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "mariadb-galeria.fullname" . }}
    spec:
      containers:
      - name: mariadb-galeria
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysqlRootPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysqlDatabase | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysqlUser | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysqlPassword | quote }}
        - name: MARIA_DB_GALERA_CLUSTER_BOOTSTRAP
          value: "yes"
        - name: MARIA_DB_GALERA_CLUSTER_ADDRESS
          value: "gcomm://{{ include "mariadb-galeria.fullname" . }}-0.{{ include "mariadb-galeria.fullname" . }}-headless.default.svc.cluster.local,{{ include "mariadb-galeria.fullname" . }}-1.{{ include "mariadb-galeria.fullname" . }}-headless.default.svc.cluster.local,{{ include "mariadb-galeria.fullname" . }}-2.{{ include "mariadb-galeria.fullname" . }}-headless.default.svc.cluster.local"
        - name: MARIA_DB_GALERA_NODE_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
      volumes:
      - name: mariadb-galeria-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
  volumeClaimTemplates:
  - metadata:
      name: mariadb-persistent-storage
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
