apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "charts.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "charts.fullname" . }}
  serviceName: "{{ include "charts.fullname" . }}-headless"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "charts.fullname" . }}
    spec:
      containers:
      - name: charts
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysqlRootPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysqlDatabase | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysqlUser | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysqlPassword | quote }}
        - name: charts_GALERA_CLUSTER_BOOTSTRAP
          value: "yes"
        - name: charts_GALERA_CLUSTER_ADDRESS
          value: "gcomm://{{ include "charts.fullname" . }}-0.{{ include "charts.fullname" . }}-headless.default.svc.cluster.local,{{ include "charts.fullname" . }}-1.{{ include "charts.fullname" . }}-headless.default.svc.cluster.local,{{ include "charts.fullname" . }}-2.{{ include "charts.fullname" . }}-headless.default.svc.cluster.local"
        - name: charts_GALERA_NODE_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: charts-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: charts-persistent-storage
        persistentVolumeClaim:
          claimName: charts-pvc
  volumeClaimTemplates:
  - metadata:
      name: charts-persistent-storage
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
