replicaCount: 3

image:
  repository: mariadb
  tag: "10.5"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3306
  loadBalancer:
    enabled: true

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

nodeSelector: {}

tolerations: []

affinity: []

mysqlRootPassword: "root_password"
mysqlDatabase: "testdb"
mysqlUser: "testuser"
mysqlPassword: "testpassword"
