version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          command: cat publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: cleverom/db-charts
            - GITHUB_PAGES_BRANCH: gh-pages
            - HELM_VERSION: 3.4.2

  setup:
    docker:
      - image: circleci/python:3.8
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install Helm
          command: |
            curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - run:
          name: Install yq
          command: |
            sudo pip install yq

    deploy:
      docker:
        - image: alpine
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Deploy to Cloud Platform
        - run: 
           name: 
           command: | 
            export CHARTNAME="mariadb-galera"
            ./deploy.sh $CHARTNAME
          env: 
            CLOUD_PLATFORM: ${{ secrets.CLOUD_PLATFORM }}
            GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            GCP_KEY_FILE: ${{ secrets.GCP_KEY_FILE }}

workflows:
  version: 2
  pipeline:
    jobs:
    - build:
       context: credentials
    - setup:
        context: credentials
        requires:
          - build
    # - deploy:
    #     context: credentials
    #     requires:
    #       - setup