version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          command: cat publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: cleverom/db-charts
            - GITHUB_PAGES_BRANCH: gh-pages
            - HELM_VERSION: 3.4.2
